### ISSUE TITLE
run_waterkit.py failed

### ISSUE THREAD

**Issue by xiedq** [forlilab/waterkit#4] opened 2023-01-11 09:36 UTC
We tried to use waterkit to predict the distribution of water molecules near the binding site of protein-small molecule complex, but if  the small molecule contains Cl atoms, when run the step run_waterkit.py, an error occurred.

run_waterkit.py -i  com_prepared_amber.pdbqt -c 26.95 6.16 4.15 -s 23 23 23 -n 10000 -j 16 -o traj 

PDBQT parsing error: Atom type CL is not a valid AutoDock type (atom types are case-sensitive).
 > ATOM   2610 Cl1  BNZ A 163      29.032   7.968   2.789  1.00  1.00    -0.097 CL

 in our input amber_pdbqt file:
ATOM   2611  Cl1 BNZ A 163      29.032   7.968   2.789  1.00  1.00    -0.097 cl

[com_prepared_amber.zip](https://github.com/forlilab/waterkit/files/10390815/com_prepared_amber.zip)

**Comment by jeeberhardt** [comment] 2023-01-11 12:27
Hi,

Thanks for the feedback! The issue is fixed now (add19c52b4b1baf31b7fa44067fca3d6d17f6402). 

Best,
Jerome.

**Closed as completed** 2023-09-07 12:21 UTC
